language: python

python:
  - "3.8"

install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev

script:
  - mypy -m ./telegram-clone-py/backend
  - mypy -m ./telegram-clone-py/frontend
